package tamanbermain.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Area_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Restoran_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new TamanBermain_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Toko_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Wahana_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d17L), MetaIdFactory.conceptId(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d45L), MetaIdFactory.conceptId(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d10L), MetaIdFactory.conceptId(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d4bL), MetaIdFactory.conceptId(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d3dL)).seal();
}
