package tamanbermain.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Area;
  private ConceptPresentation props_Restoran;
  private ConceptPresentation props_TamanBermain;
  private ConceptPresentation props_Toko;
  private ConceptPresentation props_Wahana;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Area:
        if (props_Area == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Area");
          props_Area = cpb.create();
        }
        return props_Area;
      case LanguageConceptSwitch.Restoran:
        if (props_Restoran == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Restoran");
          props_Restoran = cpb.create();
        }
        return props_Restoran;
      case LanguageConceptSwitch.TamanBermain:
        if (props_TamanBermain == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("TamanBermain");
          props_TamanBermain = cpb.create();
        }
        return props_TamanBermain;
      case LanguageConceptSwitch.Toko:
        if (props_Toko == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Toko");
          props_Toko = cpb.create();
        }
        return props_Toko;
      case LanguageConceptSwitch.Wahana:
        if (props_Wahana == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Wahana");
          props_Wahana = cpb.create();
        }
        return props_Wahana;
    }
    return null;
  }
}
