package tamanbermain.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Area = 0;
  public static final int Restoran = 1;
  public static final int TamanBermain = 2;
  public static final int Toko = 3;
  public static final int Wahana = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L);
    builder.put(0x446f6b5c33816d17L, Area);
    builder.put(0x446f6b5c33816d45L, Restoran);
    builder.put(0x446f6b5c33816d10L, TamanBermain);
    builder.put(0x446f6b5c33816d4bL, Toko);
    builder.put(0x446f6b5c33816d3dL, Wahana);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
