package tamanbermain.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptArea = createDescriptorForArea();
  /*package*/ final ConceptDescriptor myConceptRestoran = createDescriptorForRestoran();
  /*package*/ final ConceptDescriptor myConceptTamanBermain = createDescriptorForTamanBermain();
  /*package*/ final ConceptDescriptor myConceptToko = createDescriptorForToko();
  /*package*/ final ConceptDescriptor myConceptWahana = createDescriptorForWahana();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptArea, myConceptRestoran, myConceptTamanBermain, myConceptToko, myConceptWahana);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Area:
        return myConceptArea;
      case LanguageConceptSwitch.Restoran:
        return myConceptRestoran;
      case LanguageConceptSwitch.TamanBermain:
        return myConceptTamanBermain;
      case LanguageConceptSwitch.Toko:
        return myConceptToko;
      case LanguageConceptSwitch.Wahana:
        return myConceptWahana;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForArea() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tamanbermain", "Area", 0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d17L);
    b.class_(false, false, false);
    b.origin("r:5a7f72ac-5109-4495-b5c6-83d175c2e871(tamanbermain.structure)/4931278160739265815");
    b.version(3);
    b.property("name", 0x446f6b5c33816d25L).type(PrimitiveTypeId.STRING).origin("4931278160739265829").done();
    b.property("luas", 0x446f6b5c33816d27L).type(PrimitiveTypeId.INTEGER).origin("4931278160739265831").done();
    b.aggregate("wahana", 0x446f6b5c33816e96L).target(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d3dL).optional(true).ordered(true).multiple(true).origin("4931278160739266198").done();
    b.aggregate("restoran", 0x446f6b5c33816e97L).target(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d45L).optional(true).ordered(true).multiple(true).origin("4931278160739266199").done();
    b.aggregate("toko", 0x446f6b5c33816e9bL).target(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d4bL).optional(true).ordered(true).multiple(true).origin("4931278160739266203").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRestoran() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tamanbermain", "Restoran", 0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d45L);
    b.class_(false, false, false);
    b.origin("r:5a7f72ac-5109-4495-b5c6-83d175c2e871(tamanbermain.structure)/4931278160739265861");
    b.version(3);
    b.property("name", 0x446f6b5c33816d47L).type(PrimitiveTypeId.STRING).origin("4931278160739265863").done();
    b.property("kapasitas", 0x446f6b5c33816d48L).type(PrimitiveTypeId.INTEGER).origin("4931278160739265864").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTamanBermain() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tamanbermain", "TamanBermain", 0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d10L);
    b.class_(false, false, true);
    b.origin("r:5a7f72ac-5109-4495-b5c6-83d175c2e871(tamanbermain.structure)/4931278160739265808");
    b.version(3);
    b.property("name", 0x446f6b5c33816d2aL).type(PrimitiveTypeId.STRING).origin("4931278160739265834").done();
    b.aggregate("areas", 0x446f6b5c33816d2cL).target(0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d17L).optional(true).ordered(true).multiple(true).origin("4931278160739265836").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForToko() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tamanbermain", "Toko", 0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d4bL);
    b.class_(false, false, false);
    b.origin("r:5a7f72ac-5109-4495-b5c6-83d175c2e871(tamanbermain.structure)/4931278160739265867");
    b.version(3);
    b.property("name", 0x446f6b5c33816d4dL).type(PrimitiveTypeId.STRING).origin("4931278160739265869").done();
    b.property("kapasitas", 0x446f6b5c33816d4eL).type(PrimitiveTypeId.INTEGER).origin("4931278160739265870").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWahana() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("tamanbermain", "Wahana", 0xc5a333dc5e9d4806L, 0xb26c70c4ffe104e3L, 0x446f6b5c33816d3dL);
    b.class_(false, false, false);
    b.origin("r:5a7f72ac-5109-4495-b5c6-83d175c2e871(tamanbermain.structure)/4931278160739265853");
    b.version(3);
    b.property("name", 0x446f6b5c33816d3fL).type(PrimitiveTypeId.STRING).origin("4931278160739265855").done();
    b.property("kapasitas", 0x446f6b5c33816d41L).type(PrimitiveTypeId.INTEGER).origin("4931278160739265857").done();
    b.property("durasi", 0x446f6b5c33816d43L).type(PrimitiveTypeId.INTEGER).origin("4931278160739265859").done();
    return b.create();
  }
}
